# Generated by Django 6.1 on 2026-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='committment',
            field=models.CharField(default='fulltime', max_length=100),
            preserve_default=False,
        ),
    ]
