# Generated by Django 6.1 on 2026-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_committment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='committment',
            new_name='commitment',
        ),
        migrations.AddField(
            model_name='job',
            name='Experience',
            field=models.CharField(default='fulltime', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='fulltime'),
            preserve_default=False,
        ),
    ]
