# Generated by Django 6.1 on 2026-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_committment_job_commitment_job_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
