# Generated by Django 6.1 on 2026-08-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_id_job_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Experience',
            new_name='experience',
        ),
    ]
